import codecs, re
path = 'lib/screens/story_session_screen.dart'
with codecs.open(path, 'r', 'utf-8') as f:
    text = f.read()

text = text.replace("Chip(label: Text('Language: \')),", "Chip(label: Text('Language: ')),")
text = text.replace("Chip(label: Text('\ mins')),", "Chip(label: Text(' mins')),")
text = text.replace("withOpacity(0.1)", "withValues(alpha: 0.1)")
text = text.replace("withOpacity(0.2)", "withValues(alpha: 0.2)")
text = text.replace("withOpacity(0.3)", "withValues(alpha: 0.3)")
text = text.replace("withOpacity(0.4)", "withValues(alpha: 0.4)")
text = text.replace("withOpacity(0.5)", "withValues(alpha: 0.5)")

# fix _buildOpeningPage double defined:
# Let's just comment out the second one? Or remove it completely.
# We'll just regex replace the second occurrence.

parts = text.split('Widget _buildOpeningPage(')

if len(parts) > 2:
    # First occurrence was our new code, second is the old code? Wait, maybe both were generated by me.
    # Let's keep the first array elements up to the 2nd boundary and replace the 3rd one.
    text = parts[0] + 'Widget _buildOpeningPage(' + parts[1] + '/* Widget _buildOpeningPage(' + parts[2]
    # find where the second one ends by finding the next Widget definition or similar?
    # Just wrap the rest in block comment up until Widget _buildStoryContent() or whatever is next.
    idx = text.find('Widget _buildStoryContent()')
    if idx != -1:
        text = text[:idx] + '*/\n  ' + text[idx:]

with codecs.open(path, 'w', 'utf-8') as f:
    f.write(text)

