// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2cwFqyYKHhlnMjDDMwPv3navWggTGHzg',
    appId: '1:1027680552915:web:bc84af0f17c6a570bf1126',
    messagingSenderId: '1027680552915',
    projectId: 'kuwentobuddy-57511',
    authDomain: 'kuwentobuddy-57511.firebaseapp.com',
    storageBucket: 'kuwentobuddy-57511.firebasestorage.app',
    measurementId: 'G-CR1K5693BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRbpRL6ZjEdjIToJPnoASZIjVd_H3p1M',
    appId: '1:1027680552915:android:98db5fd47d392010bf1126',
    messagingSenderId: '1027680552915',
    projectId: 'kuwentobuddy-57511',
    storageBucket: 'kuwentobuddy-57511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1pn8Qbg2e5q25WaZZxb0X5ClC5ERMjwg',
    appId: '1:1027680552915:ios:33b884373c2c9102bf1126',
    messagingSenderId: '1027680552915',
    projectId: 'kuwentobuddy-57511',
    storageBucket: 'kuwentobuddy-57511.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'kuwentobuddy',
    storageBucket: 'kuwentobuddy.appspot.com',
    iosBundleId: 'com.kuwentobuddy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2cwFqyYKHhlnMjDDMwPv3navWggTGHzg',
    appId: '1:1027680552915:web:bc84af0f17c6a570bf1126',
    messagingSenderId: '1027680552915',
    projectId: 'kuwentobuddy-57511',
    authDomain: 'kuwentobuddy-57511.firebaseapp.com',
    storageBucket: 'kuwentobuddy-57511.firebasestorage.app',
  );
}
